# SPDX-FileCopyrightText: 2024 k4leg <pOgtq@yandex.com>
#
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = "Cargo.lock"
precedence = "override"
SPDX-FileCopyrightText = "2024 k4leg <pOgtq@yandex.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "static/*.png"
precedence = "override"
SPDX-FileCopyrightText = "2024 k4leg <pOgtq@yandex.com>"
SPDX-License-Identifier = "CC-BY-SA-4.0"
